sudo: required
language: php
dist: trusty

php:
  - 7.0

before_script:
  - cd /Webapp/
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate
  # Dusk
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.example .env
  - php artisan serve &

before_install:
  - mysql -e 'CREATE DATABASE dabster;'

install:
  - travis_retry composer install --no-interaction

script:
  - Webapp/vendor/bin/phpunit
  - cd Webapp && php artisan dusk

services:
  - mysql

cache:
  directories:
    - Webapp/node_modules
    - Webapp/vendor

env:
  - TRAVIS_NODE_VERSION="4"
  
notifications:
    slack: dabsterteam:9aTVzD0L1r4lMAIYDOjmhbSm
